In [1]:
from mbte import price_simulation, statistics
import numpy as np
import pandas as pd
from matplotlib import pyplot
import random
%matplotlib inline

In [2]:
dir(statistics)

['GBMParameters',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'dataclass',
 'generate_log_returns',
 'math',
 'np',
 'random']

In [3]:
help(statistics.GBMParameters)

Help on class GBMParameters in module mbte.statistics:

class GBMParameters(builtins.object)
 |  GBMParameters(mu: float, sigma: float) -> None
 |
 |  GBMParameters(mu: float, sigma: float)
 |
 |  Methods defined here:
 |
 |  __delattr__(self, name)
 |      Implement delattr(self, name).
 |
 |  __eq__(self, other)
 |      Return self==value.
 |
 |  __hash__(self)
 |      Return hash(self).
 |
 |  __init__(self, mu: float, sigma: float) -> None
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __post_init__(self)
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  __setattr__(self, name, value)
 |      Implement setattr(self, name, value).
 |
 |  generate_log_return(self, dt: float, rng: random.Random)
 |      generates log return:
 |      ln(P_1/P_0) = ln(P_1) - ln(P_0)
 |                  = (mu - sigma**2 / 2) * dt + sigma * sqrt(dt) * epsilon
 |      where
 |          1. don't forgot the drift corection term
 |          2. epsilon ~ N(0, 1)
 |
 |  ----

In [4]:
gbm1 = statistics.GBMParameters(0.001, 0.05) 

In [5]:
statistics.generate_log_returns(gbm1, 10, 1, random.Random())

array([ 0.04894684,  0.0540892 ,  0.05332671, -0.04500919, -0.00485478,
       -0.0110317 ,  0.01148119, -0.038495  , -0.01634342, -0.06156569])

In [6]:
price_simulation.generate_gbm_prices(gbm1, 1.0, 20, random.Random()) 

(array([ 0.00676453, -0.01864827,  0.07699125,  0.04107718,  0.01288177,
         0.02388537,  0.03450962,  0.09215358,  0.06329363,  0.05390311,
        -0.08241737, -0.0558743 , -0.04797931, -0.00293122, -0.05407103,
         0.07012277, -0.14696429,  0.01430464, -0.0229681 ]),
 array([1.        , 1.00678746, 0.98818659, 1.06727376, 1.11202724,
        1.12644477, 1.15367423, 1.19418202, 1.30946025, 1.39501987,
        1.47227934, 1.35580369, 1.28212659, 1.22206346, 1.21848657,
        1.15435131, 1.23820323, 1.06897156, 1.08437271, 1.05975057]))

NameError: name 'x' is not defined